apiVersion: v1
kind: Pod
metadata:
  name: security-context
  namespace: handson
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: security-context
    emptyDir: {}
  containers:
  - name: security-context
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: security-context
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
